### ISSUE TITLE
[Bug?!]: MySQL 5.5无法查询面包数量

### ISSUE THREAD

**Issue by Emerald-AM9** [Abjust/2kbot#12]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 如果你正在使用修改过的2kbot版本：我确定这个bug是由于2kbot本身的代码缺陷导致的，而非修改版本中修改过的部分所存在的缺陷。
- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我十分肯定，绝对不是因为我菜才这样。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。

### 使用的2kbot版本

Mica App 5.1.2

### 重现步骤

给一个机器人在里面的群新建一个面包厂，然后查询面包

### 期望的结果是什么？

得到面包数量反馈

### 实际的结果是什么？

显示本群没有面包厂

### 补充说明（可选）

使用MySQL5.5（这也说明了说不定是适配不好）

**Comment by Abjust** [comment]
经过排查，是mysql初始化语句的问题
